<<<<<<< HEAD
name: Preview Hosting on PR
=======
name: Firebase Hosting PR Preview (Flutter Web)
>>>>>>> 3dd1e86 (ci(hosting): add Flutter web build & Firebase Hosting PR preview)

on:
  # Run automatically for PRs targeting main
  pull_request:
    branches: [ main ]
  # Allow manual runs from the Actions tab (helpful for debugging)
  workflow_dispatch:

<<<<<<< HEAD
jobs:
  build_and_preview:
=======
permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build_and_preview:
    # Only run if the PR comes from the same repo (skip forks unless you allow them)
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository }}
>>>>>>> 3dd1e86 (ci(hosting): add Flutter web build & Firebase Hosting PR preview)
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4

      # Setup Flutter (stable)
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Flutter version
        run: flutter --version
=======
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
>>>>>>> 3dd1e86 (ci(hosting): add Flutter web build & Firebase Hosting PR preview)

      - name: Install deps
        run: flutter pub get

<<<<<<< HEAD
      - name: Build Flutter web
        run: flutter build web --release

      # Deploy a preview channel for this PR
      - name: Deploy Preview to Firebase Hosting
=======
      - name: Build Flutter web (release)
        run: flutter build web --release

      # Deploy a preview channel to Firebase Hosting.
      # Requires:
      #   - firebase.json at repo root (points "public" to build/web)
      #   - Secret FIREBASE_SERVICE_ACCOUNT_NETECH_POS_PRODUCTION
      #   - Correct "projectId" below (your prod project id)
      - name: Deploy preview to Firebase Hosting
>>>>>>> 3dd1e86 (ci(hosting): add Flutter web build & Firebase Hosting PR preview)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NETECH_POS_PRODUCTION }}'
<<<<<<< HEAD
          projectId: netech-pos-production
          channelId: 'pr-${{ github.event.number }}'
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
=======
          projectId: 'netech-pos-production'    # <-- your production Firebase project id
          # Optional: make the channel explicit and expire in 7 days
          channelId: 'pr-${{ github.event.number }}'
          expires: 7d
          # Uses firebase.json at repo root; make sure "public": "build/web"
>>>>>>> 3dd1e86 (ci(hosting): add Flutter web build & Firebase Hosting PR preview)
