// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQUQaV7ToQoKTEIm5AIAPuaRpxmMMB9lA',
    appId: '1:188179769382:web:cc30b159b10c3159b81ee7',
    messagingSenderId: '188179769382',
    projectId: 'netech-pos-production',
    authDomain: 'netech-pos-production.firebaseapp.com',
    storageBucket: 'netech-pos-production.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUEZB5kVAoPiL__tbVyiBPjBF4ukjLsu8',
    appId: '1:188179769382:android:b3d7aba6e1b12eb5b81ee7',
    messagingSenderId: '188179769382',
    projectId: 'netech-pos-production',
    storageBucket: 'netech-pos-production.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXqKcfnYxd2BV7FZMjSJCtGbuaA4PnWdc',
    appId: '1:188179769382:ios:e2f654d1e701fa98b81ee7',
    messagingSenderId: '188179769382',
    projectId: 'netech-pos-production',
    storageBucket: 'netech-pos-production.firebasestorage.app',
    iosBundleId: 'com.example.netechPos',
  );

}