// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD24I7iZXXwSM63rIFg0xdtlj7qFQikFI',
    appId: '1:450687509485:web:55e0d18c8739320f9b3de4',
    messagingSenderId: '450687509485',
    projectId: 'netech-pos-d382f',
    authDomain: 'netech-pos-d382f.firebaseapp.com',
    storageBucket: 'netech-pos-d382f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgSUMjme2nK8fAQsohMB3utiCDTx3wjVk',
    appId: '1:450687509485:android:3c8956511ac986289b3de4',
    messagingSenderId: '450687509485',
    projectId: 'netech-pos-d382f',
    storageBucket: 'netech-pos-d382f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QRJIWdCe6XDdLsPfMlLuNClUE2YB8t4',
    appId: '1:450687509485:ios:5f922ab00bbb002d9b3de4',
    messagingSenderId: '450687509485',
    projectId: 'netech-pos-d382f',
    storageBucket: 'netech-pos-d382f.firebasestorage.app',
    iosBundleId: 'com.example.netechPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD24I7iZXXwSM63rIFg0xdtlj7qFQikFI',
    appId: '1:450687509485:web:55e0d18c8739320f9b3de4',
    messagingSenderId: '450687509485',
    projectId: 'netech-pos-d382f',
    authDomain: 'netech-pos-d382f.firebaseapp.com',
    storageBucket: 'netech-pos-d382f.firebasestorage.app',
  );

}